### ISSUE TITLE
내용수정 | git commit --ammend -> git commit --amend

### ISSUE THREAD

**Issue by katepark1009** [corean/git-study#1]
Git 요약글 감사합니다! 
몰랐던 내용도 많아서 저장해놓고 넘 유용하게 잘 보고있습니다.
중간에 오타가 있으신것 같아서 혹시나하고 알려드리려고 이슈를 남깁니다.

용어 > Commit > 5번째 불렛포인트
`git commit --ammend` -> `git commit --amend`

좋은 글 감사합니다!^^

**Comment by corean** [comment]
넵 적용했습니다
